### ISSUE TITLE
QG Naming Inconsistency

### ISSUE THREAD

**Issue by Steven-Roberts** [ComputationalScienceLaboratory/ODE-Test-Problems#51]
Our convention is a problem should have the same name as the package it's in. But `QuasiGeostrophicProblem` is in a package named `qg`. I suggest renaming the package to `quasigeostrophic` for consistency. Any issues with backwards compatibility or papers that reference qg @AndreyAPopov?

**Comment by AndreyAPopov** [comment]
I typically copy and paste a version of OTP and DATools into every project that I work on so that if there are breaking changes in the main branch, they would not effect my project, so I can change this pretty easily. I never put code in any papers, so that would have no effect. I usually say (Quasi-Geostrophic equation (QG)), like that, and just say the implementation is taken from OTP.

I will fix it in the QG pull request I have open.
