### ISSUE TITLE
problem.solve does not support alternate RHS

### ISSUE THREAD

**Issue by AndreyAPopov** [ComputationalScienceLaboratory/ODE-Test-Problems#59]
Title. It would help a lot with testing if this was possible.

**Comment by Steven-Roberts** [comment]
Hmm, I wish we could move solve functionality into RHS but it needs access to the Problem for events. What is the use case? Testing the alternate QG RHS? Anything else?

**Comment by Steven-Roberts** [comment]
Events make it tricky to switch out an RHS because the problem can change.
https://github.com/ComputationalScienceLaboratory/ODE-Test-Problems/blob/c9ec2386d25f9bccac84f1d70bb32fdef755bc4f/src/%2Botp/Problem.m#L243
I think we would have to specify the alternate RHS as a string representing the name of a Problem property. Not a big fan of that solution...

**Comment by Steven-Roberts** [comment]
Closing for lack of clean solution. We'll just have to make separate tests for problems with extra RHS'
